version: '3.1'
services:
  rabbitmq:
    image: library/rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=utku
      - RABBITMQ_DEFAULT_PASS=utku

# 15672 management port